### ISSUE TITLE
盛り上がりレーダーチャートの作成

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/Aktiva-V2#18]
`ExcitementChart.unity`を編集する。
* 今回は配置するだけ（現状のデータから取得する必要はない）

## デザイン案
![default](https://user-images.githubusercontent.com/13435109/28434951-3b7026ec-6dcc-11e7-9c7d-4bf0dbbcd0b6.png)

## 素材
https://drive.google.com/drive/u/0/folders/0B5og1PuOXWEBZGZ1SWR5YjVtTXM

**Comment by mori-atsushi** [comment]
@ehnh アイコンとかの素材アップロードお願いしやす！

**Comment by mori-atsushi** [comment]
@ehnh あと、この五角形の画像ください（５つまとめて、角の円含めて）
![2017-07-26 19 09 21](https://user-images.githubusercontent.com/13435109/28615988-fcba630e-7235-11e7-9c72-70b7f64beaef.png)

**Comment by mori-atsushi** [comment]
@ehnh あと、フォント名、カラーコードの一覧も頼む。

**Comment by ehnh** [comment]
ドライブの「盛り上がり度」フォルダにpentagon.pngをあげました。
フォントは、盛り上がり度の部分はヒラギノ角ゴstdN、それ以外はproN W6でいいかなー。
色は#27a0b3と#ffffff
チャート部分は透過50%

**Comment by mori-atsushi** [comment]
@ehnh  Windowsで動かすからヒラギノ角ゴって無理なんよね…

**Comment by ehnh** [comment]
んじゃ游ゴシックboldかな？

**Comment by meokz** [comment]
めっちゃ大きいんだけどこれはいいんだっけ

![2017-08-03 21 01 42](https://user-images.githubusercontent.com/2770950/28920964-097b34a6-788f-11e7-9a13-3c43de795520.png)
